import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'

const output = join(process.cwd(), 'out')
const basePath = (process.env.NEXT_PUBLIC_BASE_PATH ?? '').replace(/\/$/, '')
const files = await walk(output)
const assets = []
const digest = createHash('sha256')

// The social card is for crawlers, never for the user. Precaching it would
// spend 120KB of a first-run download that has to finish before anyone reaches
// a place with no cell service, on an image the app never displays.
const NEVER_PRECACHE = new Set(['sw.js', 'og-image.png'])

/**
 * Turbopack emits both halves of MapLibre's dev/production export condition,
 * and the production build only ever resolves the production half — verified by
 * recording every maplibre request a production page makes. Precaching the dev
 * twins costs 2.2MB, a fifth of an install that is all-or-nothing: every byte
 * is another chance for the whole thing to fail on a tethered phone. They stay
 * on the server, so the dev branch would still resolve if it were ever taken.
 */
const isDevBundle = (pathname) => /-dev\.[0-9a-z_]+\.mjs$/.test(pathname)

let skippedBytes = 0
for (const file of files.sort()) {
  const pathname = relative(output, file).split(sep).join('/')
  // Share cards and the pages that carry them exist for crawlers. There are
  // hundreds of them and the app never shows one.
  if (pathname.startsWith('share/') || pathname.startsWith('p/')) continue
  if (NEVER_PRECACHE.has(pathname) || pathname.endsWith('.map')) continue
  const bytes = await readFile(file)
  if (isDevBundle(pathname)) {
    skippedBytes += bytes.length
    continue
  }
  digest.update(pathname).update(bytes)
  const route = pathname === 'index.html' ? '' : pathname
  assets.push(`${basePath}/${route}`)
}

const cacheName = `dust-compass-${digest.digest('hex').slice(0, 12)}`
const shell = `${basePath}/`
const dataPrefix = `${basePath}/data/`
const source = `/* Generated by scripts/build-sw.mjs. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(assets, null, 2)};
const SHELL = ${JSON.stringify(shell)};
const DATA_PREFIX = ${JSON.stringify(dataPrefix)};

async function notify(message) {
  const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  for (const client of windows) client.postMessage(message);
}

// A precache that gives up on the first hiccup is the failure mode that matters
// here: the download happens on whatever connection someone has before they
// drive out, and there is no second chance once they are on playa. Each asset
// gets three attempts with backoff, and several are in flight at once so an
// 8MB install is not sixty serial round trips over a tethered phone.
const ATTEMPTS = 3;
const PARALLEL = 6;
// A hotspot that accepts the connection and never answers would otherwise park
// the install until the browser kills the worker, which looks like progress.
const REQUEST_TIMEOUT_MS = 20000;

async function store(cache, url) {
  // The cache name is a content hash of the build, so anything already in it is
  // provably the right bytes. Retrying an install must not re-download 8MB.
  if (await cache.match(url)) return;
  let failure;
  for (let attempt = 0; attempt < ATTEMPTS; attempt += 1) {
    if (attempt > 0) await new Promise((resolve) => setTimeout(resolve, 300 * Math.pow(2, attempt - 1)));
    try {
      const response = await fetch(new Request(url, {
        cache: 'reload',
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      }));
      if (!response.ok) throw new Error('HTTP ' + response.status);
      await cache.put(url, response);
      return;
    } catch (error) {
      failure = error;
    }
  }
  throw failure;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    let completed = 0;
    try {
      const cache = await caches.open(CACHE_NAME);
      const queue = PRECACHE.slice();
      let failed = null;

      // Install still fails as a whole if anything is unreachable. A partial
      // cache that reported success would be a lie told at the worst moment.
      async function drain() {
        while (queue.length > 0 && failed === null) {
          const url = queue.shift();
          try {
            await store(cache, url);
          } catch (error) {
            failed = { url: url, reason: String((error && error.message) || error) };
            return;
          }
          completed += 1;
          await notify({ type: 'CACHE_PROGRESS', completed, total: PRECACHE.length });
        }
      }

      await Promise.all(Array.from({ length: Math.min(PARALLEL, queue.length) }, drain));
      if (failed !== null) throw new Error('Could not cache ' + failed.url + ': ' + failed.reason);
    } catch (error) {
      // Every failure path reports. caches.open itself throws when storage is
      // already full, and that used to leave the chip saying "Preparing
      // offline" forever — which reads as progress, not as failure.
      await notify({ type: 'CACHE_FAILED', completed, total: PRECACHE.length });
      // A half-filled cache is never the active worker's, since the name is a
      // hash of this build. Leaving it behind makes the next quota failure more
      // likely for the one person already struggling with signal.
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // Deliberately no skipWaiting here. Taking over the moment a new version
    // finishes installing means the open tab gets reloaded underneath whoever
    // is reading it — the page renders, then renders again a second later.
    // The new worker waits, the status chip says "Update ready", and the reload
    // happens when the user asks for it.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith('dust-compass-') && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
    await notify({ type: 'OFFLINE_READY', total: PRECACHE.length });
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') void self.skipWaiting();
});

/** Only this build's cache. An unscoped match reads other versions' caches. */
async function fromCache(request) {
  const cache = await caches.open(CACHE_NAME);
  return cache.match(request);
}

/**
 * The listings keep moving after a build ships — most importantly, art
 * locations become publishable when Gates open. Serve what is cached so the
 * map is instant and works offline, and quietly refresh it behind the reader.
 * Only a same-origin JSON response replaces anything: a captive portal answers
 * every request with its own login page, and it answers with HTML.
 */
async function refreshData(request) {
  try {
    const response = await fetch(request, { signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS) });
    const type = response.headers.get('content-type') || '';
    if (response.ok && type.includes('json')) {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(request, response.clone());
    }
    return response;
  } catch {
    return undefined;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  /**
   * Navigations are answered from the cache and never write to it.
   *
   * Writing them back was poisoning the precache in two ways. A captive portal
   * returns its login page with 200 OK, which then replaced the app shell
   * permanently — every later offline launch opened the Wi-Fi login screen,
   * with no way back on playa. And when a new deploy's HTML arrived but its
   * install then failed on a weak connection, the old cache was left holding
   * new HTML that names chunks which exist nowhere on the device: a blank
   * screen, unrecoverable once the server drops the old chunks.
   *
   * The shell is precached, and new versions arrive through the worker update
   * lifecycle. The network is the last resort here, not the first.
   */
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      const exact = await cache.match(request);
      if (exact) return exact;

      // A listing page is a real page on the server and is deliberately not
      // precached, so it has to be fetched — but never written back, which is
      // what was poisoning the shell. Falling straight through to SHELL here
      // served the app at /p/<uid>/ with no listing in the URL, so every
      // shared link opened the bare city once a cache existed.
      try {
        const network = await fetch(request);
        if (network.ok) return network;
      } catch {
        /* offline, or the page has gone; fall through */
      }

      // Offline, a shared listing link still has somewhere to go: the app is
      // cached, and the listing travels as a query parameter instead of a path.
      const listing = /[/]p[/]([^/]+)[/]?$/.exec(url.pathname);
      if (listing) {
        return Response.redirect(SHELL + '?poi=' + encodeURIComponent(listing[1]), 302);
      }

      const shell = await cache.match(SHELL);
      if (shell) return shell;
      return fetch(request);
    })());
    return;
  }

  if (url.pathname.startsWith(DATA_PREFIX)) {
    event.respondWith((async () => {
      const cached = await fromCache(request);
      if (cached) {
        event.waitUntil(refreshData(request));
        return cached;
      }
      return (await refreshData(request)) || fetch(request);
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await fromCache(request);
    if (cached) return cached;
    // Anything not precached — a share card, a listing page — is fetched and
    // handed straight back. Writing it into this build's cache would grow the
    // offline install with things the app never shows.
    return fetch(request);
  })());
});
`

await writeFile(join(output, 'sw.js'), source)
const skippedNote = skippedBytes
  ? ` (${(skippedBytes / 1024 / 1024).toFixed(2)}MB of unused dev bundles left out)`
  : ''
console.log(
  `Generated ${join('out', 'sw.js')} with ${assets.length} offline assets (${cacheName})${skippedNote}.`,
)

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name)
      return entry.isDirectory() ? walk(path) : [path]
    }),
  )
  return nested.flat()
}
