import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'

const output = join(process.cwd(), 'out')
const basePath = (process.env.NEXT_PUBLIC_BASE_PATH ?? '').replace(/\/$/, '')
const files = await walk(output)
const assets = []
const digest = createHash('sha256')

// The social card is for crawlers, never for the user. Precaching it would
// spend 120KB of a first-run download that has to finish before anyone reaches
// a place with no cell service, on an image the app never displays.
const NEVER_PRECACHE = new Set(['sw.js', 'og-image.png'])

for (const file of files.sort()) {
  const pathname = relative(output, file).split(sep).join('/')
  if (NEVER_PRECACHE.has(pathname) || pathname.endsWith('.map')) continue
  const bytes = await readFile(file)
  digest.update(pathname).update(bytes)
  const route = pathname === 'index.html' ? '' : pathname
  assets.push(`${basePath}/${route}`)
}

const cacheName = `dust-compass-${digest.digest('hex').slice(0, 12)}`
const shell = `${basePath}/`
const source = `/* Generated by scripts/build-sw.mjs. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(assets, null, 2)};
const SHELL = ${JSON.stringify(shell)};

async function notify(message) {
  const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  for (const client of windows) client.postMessage(message);
}

// A precache that gives up on the first hiccup is the failure mode that matters
// here: the download happens on whatever connection someone has before they
// drive out, and there is no second chance once they are on playa. Each asset
// gets three attempts with backoff, and several are in flight at once so a
// 7.9MB install is not 60 serial round trips over a tethered phone.
const ATTEMPTS = 3;
const PARALLEL = 6;

async function store(cache, url) {
  let failure;
  for (let attempt = 0; attempt < ATTEMPTS; attempt += 1) {
    if (attempt > 0) await new Promise((resolve) => setTimeout(resolve, 300 * Math.pow(2, attempt - 1)));
    try {
      const response = await fetch(new Request(url, { cache: 'reload' }));
      if (!response.ok) throw new Error('HTTP ' + response.status);
      await cache.put(url, response);
      return;
    } catch (error) {
      failure = error;
    }
  }
  throw failure;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    const queue = PRECACHE.slice();
    let completed = 0;
    let failed = null;

    // Install still fails as a whole if anything is unreachable. A partial
    // cache that reported success would be a lie told at the worst moment.
    async function drain() {
      while (queue.length > 0 && failed === null) {
        const url = queue.shift();
        try {
          await store(cache, url);
        } catch (error) {
          failed = { url: url, reason: String((error && error.message) || error) };
          return;
        }
        completed += 1;
        await notify({ type: 'CACHE_PROGRESS', completed, total: PRECACHE.length });
      }
    }

    await Promise.all(Array.from({ length: Math.min(PARALLEL, queue.length) }, drain));

    if (failed !== null) {
      // Tell the tab before throwing, or the user watches a progress count
      // stall forever and drives to the desert believing the map is saved.
      await notify({ type: 'CACHE_FAILED', completed, total: PRECACHE.length, url: failed.url });
      throw new Error('Could not cache ' + failed.url + ': ' + failed.reason);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith('dust-compass-') && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
    await notify({ type: 'OFFLINE_READY', total: PRECACHE.length });
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') void self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) (await caches.open(CACHE_NAME)).put(request, response.clone());
        return response;
      } catch {
        return (await caches.match(request)) || (await caches.match(SHELL));
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response.ok) (await caches.open(CACHE_NAME)).put(request, response.clone());
    return response;
  })());
});
`

await writeFile(join(output, 'sw.js'), source)
console.log(`Generated ${join('out', 'sw.js')} with ${assets.length} offline assets (${cacheName}).`)

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name)
      return entry.isDirectory() ? walk(path) : [path]
    }),
  )
  return nested.flat()
}
