import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'

const output = join(process.cwd(), 'out')
const basePath = (process.env.NEXT_PUBLIC_BASE_PATH ?? '').replace(/\/$/, '')
const files = await walk(output)
const assets = []
const digest = createHash('sha256')

for (const file of files.sort()) {
  const pathname = relative(output, file).split(sep).join('/')
  if (pathname === 'sw.js' || pathname.endsWith('.map')) continue
  const bytes = await readFile(file)
  digest.update(pathname).update(bytes)
  const route = pathname === 'index.html' ? '' : pathname
  assets.push(`${basePath}/${route}`)
}

const cacheName = `dust-compass-${digest.digest('hex').slice(0, 12)}`
const shell = `${basePath}/`
const source = `/* Generated by scripts/build-sw.mjs. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(assets, null, 2)};
const SHELL = ${JSON.stringify(shell)};

async function notify(message) {
  const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  for (const client of windows) client.postMessage(message);
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    let completed = 0;
    for (const url of PRECACHE) {
      const response = await fetch(new Request(url, { cache: 'reload' }));
      if (!response.ok) throw new Error('Could not cache ' + url + ': ' + response.status);
      await cache.put(url, response);
      completed += 1;
      await notify({ type: 'CACHE_PROGRESS', completed, total: PRECACHE.length });
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith('dust-compass-') && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
    await notify({ type: 'OFFLINE_READY', total: PRECACHE.length });
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') void self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) (await caches.open(CACHE_NAME)).put(request, response.clone());
        return response;
      } catch {
        return (await caches.match(request)) || (await caches.match(SHELL));
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response.ok) (await caches.open(CACHE_NAME)).put(request, response.clone());
    return response;
  })());
});
`

await writeFile(join(output, 'sw.js'), source)
console.log(`Generated ${join('out', 'sw.js')} with ${assets.length} offline assets (${cacheName}).`)

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name)
      return entry.isDirectory() ? walk(path) : [path]
    }),
  )
  return nested.flat()
}
